export const en_locationText = {
    home: {
        banner: "King-Of-Invite Contest, $6000 Prize Money!",
        welcome_olduser: "Welcome to Hunters Union!",
        welcome_newuser: "Welcome to Hunters’ Union, build affiliates’ kingdom and earn passively.",
        newJoin: "Join To Earn 10,000",
        tier1: "Your Tier-1 Affiliates:",
        tier2: "Your Tier-2 Affiliates:",
        earn: "My Earnings",
        invite: "Invite More",
        join: "Join Group Chat and start earning"
    },
    leader: {
        title: "King-Of-Invite Contest: $6000 USDT to grab",
        detail: "Detail Rules:",
        rule: "To celebrate the milestone, Tele Hunter presents, $6000 USDT prize pool to grab lasting 6 weeks starting from Nov, 11th. Zero threshold, free to participate, everyone is equal. Invite more, improve your Ranking, Higher Chance to win.",
        reward1: "* No. 1: $1000 USDT",
        reward2: "* No. 2 ~ 3: $500 USDT",
        reward3: "* No. 4 ~ 10: $200 USDT",
        reward4: "* No. 11 ~ 80: $35 USDT",
        other: "Extra giveaway campaigns, total $1000.",
        ranking: "Your Ranking",
        youearn: "(You can win $1000 at most)",
        invite: "Invite More To Improve Your Ranking",
        tableRank: "Ranking",
        handle: "TG-Handle",
        table3: "Tier-1 Affiliates",
        table4: "Tier-2 Affiliates",
    },
    dashboard: {
        well: "Well Done! ",
        start: "Start your own traffic business!",
        totalPoint: "Total $Hunter Point:",
        pointRank: "Your Point Ranking:",
        tier1: "Your Total Tier-1 Affiliates:",
        tier2: "Your Total Tier-2 Affiliates:",
        descTitle: "Your Affiliate Kingdom",
        rule: "Affiliate Expansion Rules:",
        rule1: "1. A direct invite is deemed as a Tier-1 affiliate, earns you 20,000 $Hunter Score.",
        rule2: "2. Tier-1 Affiliate's direct invite is deemed as your Tier-2 affiliate, earns you 40,000 $Hunter Score.",
        rule3: "3. Push and Help your Tier-1 Affiliates to invite more, you’ll earn more.",
        noAffiliate: "You have no Tier-1 affiliates, share to get more affiliates.",
        table1: "TG-Handle",
        table2: "Tier-2 Affiliates",
        table3: "Revenue Contribution",
        push: "Push!",
    },
    wiki: {
        title: "Frequently Asked Questions",
        q1: "Q1. What is Tele-Hunter?",
        q2: "Q2. What is the Multi-tier Referral Affiliate System in TeleHunter?",
        q3: "Q3. What are the benefits of building a Multi-tier Referral Affiliate System?",
        q4: "Q4. How can I build my Multi-tier referral affiliate system?",
        q5: "Q5. Can a newbie without influence make money at TeleHunter?",
        q6: "Q6. What is the Inverted Pyramid Profit Sharing Mechanism?",
        q7: "Q7. What do I earn with TeleHunter during the MVP stage?",
        q8: "Q8. Is using TeleHunter free and safe?",
        q9: "Q9. What is the future of TeleHunter in the long term?",
        a1: "Answer: TeleHunter’s is dedicated to becoming the most viral user traffic growth platform on Telegram. By improving users’ bargaining power against advertisers in the online traffic business, users can earn more profits. TeleHunter will help each user build an exclusive TG traffic affiliate system, launching your first traffic monetization business with one click, and earn your first income on TG. At the same time, the unique mechanism design allows The most influential KOL helps you make money and help your business grow exponentially.",
        a2: "Answer: This is TeleHunter's first product. Users can create their own Multi-tier Referral Affiliate System, and your direct invite will become your Tier 1 affiliates, and Tier 1’s direct invite will become your Tier 2 affiliates etc.",
        a3: "Answer: Continuously earn passive income. As the owner of the entire network fission, you can continue to obtain your own benefits from subsequent promotion. This means that you can accurately quantify your value in social networks, which is impossible in the traditional single-tier Referral system. And when the network reaches a certain scale, you don't need to work personally. You only need to manage your network and make it more efficient, allowing you to continuously earn passive income. This means you actually create your own social network’ traffic business.",
        a4: "Answer: Launch Tele Hunter’s mini app, generate your exclusive link and shill around to expand your affiliates and push them to invite more.",
        a5: "Answer: Of course, because in TeleHunter, the most influential people will help you develop your business and provide you with resources. This spirit of effective altruism stems from TeleHunter’s Inverted Pyramid Profit Sharing Mechanism.",
        a6: "Answer: In case you build your own affiliate system at TeleHunter, the lower your affiliate's tier,  the higher rewards ratios you get. This means that for the most influential people, the strategy to maximize profits is to guide their affiliates, and help them start their user traffic business. This effective and altruistic design will bring benefits to ordinary users in starting their user traffic businesses.",
        a7: "Answer: In addition to the official $Hunter Point, you can also earn real money, $6000 $TON, participating  in the King-Of-Invite Contest. $Hunter Point will be converted into Hunter Token airdrops during the Platformization Stage, which is the core of the entire platform economic model.",
        a8: "Answer: Of course, in the MVP stage, you only need to use TeleHunter Mini App to join the official group to successfully build an affiliate system. All that is left to do is to continuously invite new affiliates and manage your system, so everything is completely free. And no other additional funds or data services are required, no risk and no cost.",
        a9: "Answer: Capture more value from the whole $Ton and Telegram Ecosystems by offering them real and authentic user traffic. By Introducing potential advertisers, such as project, TG group operators etc., as early TeleHunte users, you’re able to earn income and expand your social network as well. All Hunters can selectively participate based on the rewards paid by advertisers and grow them by organic viral promotions and invitations. Hence, TeleHunter will be further upgraded to become the most viral traffic growth platform on Telegram.",
    }
}

export const ru_locationText = {
    home: {
        banner: "Конкурс «Король приглашений», призовой фонд $6000!",
        welcome_olduser: "Добро пожаловать в Союз Охотников!",
        welcome_newuser: "Добро пожаловать в Союз Охотников, создавайте королевство партнеров и зарабатывайте пассивно.",
        newJoin: "Присоединяйтесь, чтобы заработать 10 000",
        tier1: "Ваши партнеры первого уровня:",
        tier2: "Ваши партнеры второго уровня:",
        earn: "Мой заработок",
        invite: "Пригласить больше",
        join: "Присоединяйтесь к групповому чату и начните зарабатывать"
    },
    leader: {
        title: "Конкурс «Король приглашений»: разыгрывается 6000 долларов США",
        detail: "Подробные правила:",
        rule: "Чтобы отметить это событие, Tele Hunter представляет призовой фонд в размере 6000 долларов США, который будет разыгрываться в течение 6 недель, начиная с 11 ноября. Нулевой порог, участие бесплатное, все равны. Приглашайте больше, улучшайте свой рейтинг, выше шанс на победу.",
        reward1: "* No. 1: $1000 USDT",
        reward2: "* No. 2 ~ 3: $500 USDT",
        reward3: "* No. 4 ~ 10: $200 USDT",
        reward4: "* No. 11 ~ 80: $35 USDT",
        other: "Дополнительные бесплатные кампании на общую сумму 1000 долларов США.",
        ranking: "Ваш рейтинг",
        youearn: "(Вы можете выиграть максимум 1000 долларов)",
        invite: "Приглашайте больше людей, чтобы улучшить свой рейтинг",
        tableRank: "Ranking",
        handle: "TG-Handle",
        table3: "Tier-1 Affiliates",
        table4: "Tier-2 Affiliates",
    },
    dashboard: {
        well: "Отличная работа!",
        start: "Начните свой собственный транспортный бизнес!",
        totalPoint: "Всего $Hunter Point:",
        pointRank: "Ваш рейтинг по очкам:",
        tier1: "Ваше общее количество партнеров уровня 1:",
        tier2: "Общее количество ваших партнеров уровня 2:",
        descTitle: "Ваше партнерское королевство",
        rule: "Правила партнерского расширения:",
        rule1: "1. Прямое приглашение считается партнером уровня 1 и приносит вам 20 000 долларов Hunter Point.",
        rule2: "2. Прямое приглашение партнера уровня 1 считается вашим партнером уровня 2 и приносит вам 40 000 долларов Hunter Point.",
        rule3: "3. Нажимайте на своих партнеров первого уровня и помогайте им приглашать больше, и вы заработаете больше.",
        noAffiliate: "У вас нет партнеров первого уровня. Поделитесь ими, чтобы привлечь больше партнеров.",
        table1: "TG-Handle",
        table2: "Tier-2 Affiliates",
        table3: "Revenue Contribution",
        push: "Толкать!",
    },
    wiki: {
        title: "Часто задаваемые вопросы",
        q1: "Q1. Что такое Теле-Хантер?",
        q2: "Q2. Что такое многоуровневая реферальная партнерская система в TeleHunter?",
        q3: "Q3. Каковы преимущества создания многоуровневой реферальной партнерской системы?",
        q4: "Q4. Как я могу построить свою многоуровневую реферальную партнерскую систему?",
        q5: "Q5. Может ли новичок без влияния заработать в TeleHunter?",
        q6: "Q6. Что такое механизм распределения прибыли в форме перевернутой пирамиды?",
        q7: "Q7. Что я получу с TeleHunter на этапе MVP?",
        q8: "Q8. Является ли использование TeleHunter бесплатным и безопасным?",
        q9: "Q9. Каково будущее TeleHunter в долгосрочной перспективе?",
        a1: "Ответ: TeleHunter стремится стать самой вирусной платформой для роста пользовательского трафика в Telegram. Улучшая переговорную позицию пользователей по отношению к рекламодателям в бизнесе онлайн-трафика, пользователи могут получать больше прибыли. TeleHunter поможет каждому пользователю создать эксклюзивную партнерскую систему TG-трафика, запустить свой первый бизнес по монетизации трафика одним щелчком мыши и получить первый доход на TG. В то же время уникальная конструкция механизма позволяет The Most влиятельный KOL помогать вам зарабатывать деньги и помогать вашему бизнесу расти в геометрической прогрессии.",
        a2: "Ответ: Это первый продукт TeleHunter. Пользователи могут создать свою собственную многоуровневую реферальную партнерскую систему, и ваше прямое приглашение станет вашим партнером уровня 1, а прямое приглашение уровня 1 станет вашим партнером уровня 2 и т. д.",
        a3: "Ответ: Постоянно получать пассивный доход. Как владелец всей сети деления, вы можете продолжать получать собственные выгоды от последующего продвижения по службе. Это означает, что вы можете точно оценить свою ценность в социальных сетях, что невозможно в традиционной одноуровневой реферальной системе. А когда сеть достигает определенного масштаба, вам не нужно работать лично. Вам нужно только управлять своей сетью и делать ее более эффективной, позволяя вам постоянно получать пассивный доход. Это означает, что вы фактически создаете свой собственный бизнес по трафику в социальных сетях.",
        a4: "Ответ: Запустите мини-приложение Tele Hunter, создайте свою эксклюзивную ссылку и продвигайте ее, чтобы расширить число своих партнеров и побудить их приглашать больше.",
        a5: "Ответ: Конечно, ведь в TeleHunter самые влиятельные люди помогут вам развивать ваш бизнес и предоставят ресурсы. Этот дух эффективного альтруизма проистекает из механизма распределения прибыли в форме перевернутой пирамиды TeleHunter.",
        a6: "Ответ: Если вы создадите собственную партнерскую систему в TeleHunter, то чем ниже уровень вашего партнера, тем более высокие коэффициенты вознаграждения вы получите. Это означает, что для самых влиятельных людей стратегия максимизации прибыли состоит в том, чтобы направлять своих партнеров и помогать им начать бизнес по привлечению пользователей. Этот эффективный и альтруистичный дизайн принесет пользу обычным пользователям при открытии своего бизнеса в области пользовательского трафика.",
        a7: "Ответ: Помимо официальных $Hunter Point, вы также можете заработать реальные деньги, $6000 $TON, участвуя в конкурсе King-Of-Invite. $Hunter Point будут конвертированы в раздачу токенов Hunter на этапе платформеризации, который является основой всей экономической модели платформы.",
        a8: "Ответ: Конечно, на этапе MVP вам нужно всего лишь использовать приложение TeleHunter Mini, чтобы присоединиться к официальной группе и успешно создать партнерскую систему. Все, что вам остается делать, это постоянно приглашать новых партнеров и управлять вашей системой, так что все это совершенно бесплатно. И никаких других дополнительных средств или услуг по передаче данных не требуется, никакого риска и никаких затрат.",
        a9: "Ответ: Получите больше пользы от всей экосистемы $Ton и Telegram, предлагая им реальный и аутентичный пользовательский трафик. Представляя потенциальных рекламодателей, таких как операторы проекта, группы TG и т. д., в качестве первых пользователей TeleHunte, вы также можете получать доход и расширять свою социальную сеть. Все Охотники могут выборочно участвовать на основе вознаграждений, выплачиваемых рекламодателями, и увеличивать их за счет органических вирусных рекламных акций и приглашений. Следовательно, TeleHunter будет модернизирован и станет самой популярной платформой для роста вирусного трафика в Telegram.",
    }
}